language : android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra
    - extra-android-support
    - extra-android-m2repository
script:
    - chmod +x ./gradle
